services:
  # Backend - NestJS API
  - type: web
    name: balancesheet-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: SUPABASE_URL
        sync: false  # Set this manually in Render dashboard
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false  # Set this manually in Render dashboard
      - key: FRONTEND_ORIGIN
        value: https://balancesheet-frontend.onrender.com
    healthCheckPath: /
    
  # Frontend - React/Vite Static Site
  - type: web
    name: balancesheet-frontend
    env: static
    region: oregon
    plan: starter
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://balancesheet-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
